{{- if .Values.fetcher.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "steam-librarian.fullname" . }}-fetcher
  labels:
    {{- include "steam-librarian.labels" . | nindent 4 }}
    app.kubernetes.io/component: fetcher
spec:
  schedule: {{ .Values.fetcher.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.fetcher.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.fetcher.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "steam-librarian.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: fetcher
    spec:
      template:
        metadata:
          labels:
            {{- include "steam-librarian.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: fetcher
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "steam-librarian.serviceAccountName" . }}
          restartPolicy: OnFailure
          initContainers:
          - name: fix-permissions
            image: busybox:1.36
            command: ['sh', '-c']
            args:
              - |
                echo "Setting ownership of /data to nobody:nogroup (65534:65534)"
                chown -R 65534:65534 /data
                chmod -R 755 /data
                echo "Permissions fixed"
            volumeMounts:
            - name: data
              mountPath: /data
            securityContext:
              runAsUser: 0  # Run as root to change ownership
              runAsNonRoot: false
          containers:
          - name: fetcher
            securityContext:
              runAsUser: 65534  # nobody user
              runAsGroup: 65534  # nogroup
              runAsNonRoot: true
            image: "{{ .Values.fetcher.image.repository }}:{{ .Values.fetcher.image.tag }}"
            imagePullPolicy: {{ .Values.fetcher.image.pullPolicy }}
            command: ["python", "src/fetcher/steam_library_fetcher.py"]
            args:
            {{- range .Values.fetcher.extraArgs }}
            - {{ . | quote }}
            {{- end }}
            env:
            - name: STEAM_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "steam-librarian.secretName" . }}
                  key: {{ .Values.steam.existingSecretKeys.steamId }}
            - name: STEAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "steam-librarian.secretName" . }}
                  key: {{ .Values.steam.existingSecretKeys.apiKey }}
            - name: DATABASE_URL
              value: "sqlite:////data/steam_library.db"
            - name: CACHE_DAYS
              value: {{ .Values.fetcher.cacheDays | quote }}
            volumeMounts:
            - name: data
              mountPath: /data
            {{- with .Values.fetcher.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: {{ include "steam-librarian.pvcName" . }}
          {{- with .Values.fetcher.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.fetcher.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.fetcher.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}