{{- if not .Values.steam.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steam-librarian.fullname" . }}-steam-secret
  labels:
    {{- include "steam-librarian.labels" . | nindent 4 }}
type: Opaque
data:
  steam-id: {{ .Values.steam.steamId | b64enc | quote }}
  steam-api-key: {{ .Values.steam.apiKey | b64enc | quote }}
{{- end }}