{{- if .Values.mcpServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "steam-librarian.fullname" . }}-mcp-server
  labels:
    {{- include "steam-librarian.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
  {{- with .Values.mcpServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mcpServer.service.type }}
  ports:
  - port: {{ .Values.mcpServer.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "steam-librarian.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
{{- end }}