# Pre-commit configuration for Steam Librarian
# Install: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Standard Python linting and formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [--line-length=999999]
        
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # Local hooks for project-specific tasks
  - repo: local
    hooks:
      - id: version-sync
        name: Sync version numbers across components
        entry: scripts/sync-versions.py
        language: python
        files: ^(src/.*/|deploy/helm/.*/)(__.*.py|Chart.yaml)$
        pass_filenames: false
        always_run: true