services:
  # Volume permissions fixer - ensures nobody user can write to the volume
  volume-permissions:
    image: alpine:latest
    volumes:
      - steam-data:/data
    command: ["chown", "-R", "65534:65534", "/data"]
    
  # Steam Library Fetcher - runs periodically to update data
  fetcher:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.fetcher
    environment:
      - STEAM_ID=${STEAM_ID}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - DATABASE_URL=sqlite:////data/steam_library.db
      - CACHE_DAYS=7
    volumes:
      - steam-data:/data
    restart: "no"
    command: ["python", "src/fetcher/steam_library_fetcher.py"]
    depends_on:
      - volume-permissions

  # MCP Server - provides the MCP interface
  mcp-server:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.mcp_server
    environment:
      - DATABASE_URL=sqlite:////data/steam_library.db
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
      - DEBUG=false
      - DEFAULT_USER=default
    volumes:
      - steam-data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - volume-permissions
      - fetcher
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Run fetcher periodically using a cron-like service
  fetcher-cron:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.fetcher
    environment:
      - STEAM_ID=${STEAM_ID}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - DATABASE_URL=sqlite:////data/steam_library.db
      - CACHE_DAYS=7
    volumes:
      - steam-data:/data
    restart: unless-stopped
    depends_on:
      - volume-permissions
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        while true; do
          echo "Running Steam Library Fetcher at $$(date)"
          python src/fetcher/steam_library_fetcher.py
          echo "Fetcher completed. Sleeping for 24 hours..."
          sleep 86400
        done

volumes:
  steam-data:
    driver: local