name: Helm Chart Validation

on:
  pull_request:
    paths:
      - 'deploy/helm/**'
      - '.github/workflows/helm-lint.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'deploy/helm/**'
      - '.github/workflows/helm-lint.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.13.0'

    - name: Lint Helm chart
      run: |
        helm lint deploy/helm/steam-librarian

    - name: Template Helm chart
      run: |
        helm template test deploy/helm/steam-librarian \
          --set steam.steamId=test-id \
          --set steam.apiKey=test-key \
          > /tmp/manifests.yaml
        
        echo "## Generated Kubernetes Manifests" >> $GITHUB_STEP_SUMMARY
        echo "Chart templated successfully with test values" >> $GITHUB_STEP_SUMMARY

    - name: Validate Kubernetes manifests
      run: |
        # Install kubeval
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo cp kubeval /usr/local/bin
        
        # Validate the generated manifests
        kubeval /tmp/manifests.yaml --strict --ignore-missing-schemas

    - name: Run Helm unit tests
      run: |
        # Install helm unittest plugin
        helm plugin install https://github.com/helm-unittest/helm-unittest.git || true
        
        # Create basic test file
        mkdir -p deploy/helm/steam-librarian/tests
        cat > deploy/helm/steam-librarian/tests/deployment_test.yaml << EOF
        suite: test deployment
        templates:
          - deployment.yaml
        tests:
          - it: should create deployment
            set:
              mcpServer.enabled: true
            asserts:
              - isKind:
                  of: Deployment
              - matchRegex:
                  path: metadata.name
                  pattern: .*-mcp-server$
        EOF
        
        # Run tests if plugin installed successfully
        helm unittest deploy/helm/steam-librarian || echo "Helm unittest not available, skipping"