name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.13.0'

    - name: Get version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Update Chart.yaml version
      run: |
        VERSION="${{ steps.get_version.outputs.VERSION }}"
        VERSION="${VERSION#v}"  # Remove 'v' prefix
        sed -i "s/^version:.*/version: ${VERSION}/" deploy/helm/steam-librarian/Chart.yaml
        sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" deploy/helm/steam-librarian/Chart.yaml

    - name: Update Python package versions
      run: |
        VERSION="${{ steps.get_version.outputs.VERSION }}"
        VERSION="${VERSION#v}"  # Remove 'v' prefix
        sed -i "s/^__version__ = .*/__version__ = \"${VERSION}\"/" src/mcp_server/__init__.py
        sed -i "s/^__version__ = .*/__version__ = \"${VERSION}\"/" src/fetcher/__init__.py
        sed -i "s/^__version__ = .*/__version__ = \"${VERSION}\"/" src/oops_all_tools/__init__.py

    - name: Package Helm chart
      run: |
        helm package deploy/helm/steam-librarian --destination .

    - name: Create Release Notes
      id: release_notes
      run: |
        cat > release_notes.md << EOF
        ## Steam Librarian ${{ steps.get_version.outputs.VERSION }}
        
        ### Docker Images
        
        This release includes the following Docker images:
        
        - **Fetcher**: \`ghcr.io/${{ github.repository }}/fetcher:${{ steps.get_version.outputs.VERSION }}\`
        - **Full MCP Server** (port 8000): \`ghcr.io/${{ github.repository }}/mcp-server:${{ steps.get_version.outputs.VERSION }}\`
        - **Tools-Only Server** (port 8001): \`ghcr.io/${{ github.repository }}/tools-server:${{ steps.get_version.outputs.VERSION }}\`
        
        ### Architecture
        
        This version features a **dual-server architecture**:
        
        - **Full MCP Server** (port 8000): Complete MCP implementation with tools, resources, prompts, and planned completions/elicitations
        - **Tools-Only Server** (port 8001): Simplified server with only tools for maximum client compatibility (Claude Desktop/Code)
        
        Choose the server that best fits your client's MCP support level.
        
        ### Installation
        
        #### Docker Compose
        
        **Run both servers:**
        \`\`\`bash
        make run-both-servers
        # Or manually:
        cd deploy/docker
        docker-compose pull
        docker-compose up -d
        \`\`\`
        
        **Run individual servers:**
        \`\`\`bash
        # Full MCP server only (port 8000)
        make run-docker
        
        # Tools-only server only (port 8001) 
        make run-docker-tools
        \`\`\`
        
        #### Helm
        
        **Install both servers:**
        \`\`\`bash
        helm install steam-librarian deploy/helm/steam-librarian \\
          --set steam.steamId=YOUR_STEAM_ID \\
          --set steam.apiKey=YOUR_API_KEY \\
          --set fetcher.image.tag=${{ steps.get_version.outputs.VERSION }} \\
          --set mcpServer.image.tag=${{ steps.get_version.outputs.VERSION }} \\
          --set toolsServer.image.tag=${{ steps.get_version.outputs.VERSION }}
        \`\`\`
        
        **Or use Make targets:**
        \`\`\`bash
        make helm-install-both
        \`\`\`
        
        ### What's Changed
        
        See [full changelog](https://github.com/${{ github.repository }}/compare/...${{ steps.get_version.outputs.VERSION }})
        EOF

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release_notes.md
        files: |
          steam-librarian-*.tgz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-helm-values:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Get version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Update default image tags in values.yaml
      run: |
        # Create temporary file for cross-platform compatibility
        # Update image tags (standard semantic versioning without 'v')
        sed "s|tag: [0-9]*\.[0-9]*\.[0-9]*|tag: ${{ steps.get_version.outputs.VERSION }}|g" deploy/helm/steam-librarian/values.yaml > values.tmp
        # Update repository URLs if needed  
        sed "s|ghcr.io/jimsantora/steam-librarian/|ghcr.io/${{ github.repository }}/|g" values.tmp > deploy/helm/steam-librarian/values.yaml
        # Clean up
        rm values.tmp

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "chore: update Helm chart image tags to ${{ steps.get_version.outputs.VERSION }}"
        title: "Update Helm chart image tags to ${{ steps.get_version.outputs.VERSION }}"
        body: |
          This PR updates the default image tags in the Helm chart to use the newly released version.
          
          - Updates fetcher image tag to `${{ steps.get_version.outputs.VERSION }}`
          - Updates full MCP server image tag to `${{ steps.get_version.outputs.VERSION }}`
          - Updates tools-only server image tag to `${{ steps.get_version.outputs.VERSION }}`
          - Updates repository URLs to use ghcr.io
          
          **Dual-Server Architecture**: This release includes both the full MCP server (port 8000) and tools-only server (port 8001) for maximum compatibility.
        branch: update-helm-${{ steps.get_version.outputs.VERSION }}
        delete-branch: true
